pipeline {
    agent any

    environment {
        POSTGRES_SECRET = credentials('jenkins-postgres-credentials')
    }

    stages {

        stage('Update Packages') {
            steps {
                sh 'apt-get update'
                sh 'apt-get install -y libpq-dev'
            }
        }

        stage('Install Python') {
            steps {
                sh 'apt-get install -y python3 python3-pip python3-venv'
            }
        }

        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/BohdanPolulikh/DQEAutomation2025'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r data_dev/requirements.txt
                    pip install -r "PyTest DQ Framework/requirements.txt"
                '''
            }
        }

        stage('Run Data Generator') {
            steps {
                sh '''
                    . venv/bin/activate
                    export PYTHONPATH=$WORKSPACE
                    python data_dev/main.py
                '''
            }
        }

        stage('Run PyTest DQ Tests') {
            steps {
                script {
                    catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                        sh '''
                        . venv/bin/activate
                        export PYTHONPATH="$WORKSPACE/PyTest DQ Framework"
                        cd "PyTest DQ Framework"
                        pytest tests -m "parquet_data" \
                            --db_host="postgres" \
                            --db_port="5432" \
                            --db_name="mydatabase" \
                            --db_user="$POSTGRES_SECRET_USR" \
                            --db_password="$POSTGRES_SECRET_PSW" \
                            --html=html_report/report.html
                    '''
                }
            }
        }
    }

        stage('Archive Test Report') {
            steps {
                archiveArtifacts artifacts: 'PyTest DQ Framework/html_report/**', allowEmptyArchive: true

                publishHTML(target: [
                    allowMissing: false,
                    keepAll: true,
                    reportDir: 'PyTest DQ Framework/html_report',
                    reportFiles: 'report.html',
                    reportName: 'HTML Test Report'
                ])
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs for details.'
        }
    }
}


